/**
 * Persian text, digits, numbers and dates.
 *
 * Everything the dashboard shows a user goes through this file, for two reasons
 * that are separate but both load-bearing.
 *
 * The first is legibility. A rial amount runs to nine digits, and
 * `1710625.0` read at a glance in a tender table is not a number a person can
 * check against a contract. Persian digits with thousands separators make the
 * magnitude visible, which is the entire point of displaying it. These are also
 * the digits the tender documents themselves use, so a figure copied out of the
 * dashboard matches the figure in the BoQ it came from.
 *
 * The second is correctness of dates, and it is the reason this file exists
 * rather than an `Intl` call. `Intl.DateTimeFormat` with the `fa-IR` calendar
 * depends on the ICU data compiled into the runtime: the browser's build, or
 * Node's, or a polyfill's. Those builds disagree at the edges - most visibly
 * around Nowruz, where a leap-year discrepancy shifts every date in the year.
 * The defence document is a legal artifact and it is generated by the *backend*,
 * which uses the exact algorithm in `backend/src/services/_jalali_calendar.py`.
 * If this file used `Intl`, the dashboard and the document it previews could
 * disagree on the tender's own date, and the only way that is found out is by a
 * reviewer who notices. So the algorithm is mirrored here, from the same
 * reference, and `persian.test.ts` pins the two calendars against each other on
 * the dates around Nowruz where they diverge.
 *
 * The 33-year leap approximation is deliberately not used. It misidentifies
 * cycle position 17 as a leap year, which makes 1403 a 366-day year when it was
 * 365 days long - a one-day error that appears from 21 March 1404 onwards, i.e.
 * inside the forecast horizon this system produces.
 */

/** Persian (extended Arabic-Indic) digits, in value order from zero. */
const PERSIAN_DIGITS = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'] as const;

/** The separator Iranian convention uses for thousands. */
export const THOUSANDS_SEPARATOR = '٬';
/** The separator Iranian convention uses for the decimal point. */
export const DECIMAL_SEPARATOR = '٫';
/** The percent sign as written in Persian. */
export const PERCENT_SIGN = '٪';

/**
 * U+2212 MINUS SIGN, not an ASCII hyphen.
 *
 * In a right-to-left run an ASCII hyphen sits next to a strong left-to-right
 * character class - the digits - and the bidi algorithm moves it to the other
 * side of the number. `'-10'` in an RTL paragraph renders as `'10-'`, which
 * reads as a positive ten. U+2212 is classified as a mathematical symbol and
 * keeps its position. Exported because it is invisible in source: a test
 * asserting a negative figure has to name the character or it is asserting an
 * ASCII hyphen the code never produces.
 */
export const MINUS_SIGN = '\u2212';

/** The sign for a rise, as distinct from a fall. */
export const PLUS_SIGN = '+';

function toPersianDigits(input: string): string {
  return input.replace(/\d/g, (digit) => PERSIAN_DIGITS[Number(digit)]);
}

/**
 * Separators a number might already carry, stripped before re-grouping.
 *
 * The Persian thousands separator (U+066C), a plain comma, and the three space
 * variants - including U+00A0, which is what a number copied out of a rendered
 * Persian page carries, since the browser produces a non-breaking space there
 * rather than anything the user typed. Left in place, a second separator would
 * be inserted next to it and the figure would read as two numbers.
 */
const EXISTING_SEPARATORS = /[٬   ,]/g;

/**
 * Re-express a number in Persian digit and separator conventions.
 *
 * `Intl.NumberFormat('fa-IR')` would do this too, and again the ICU dependency
 * is the reason not to use it: some builds emit U+066C, others U+066B, and a
 * few emit a plain comma. The defence document's own number formatting is in
 * `backend/src/services/document_content.py` and this has to agree with it, so
 * the substitution is done explicitly and the same way on both sides.
 */
export function toPersianNumber(value: number | string): string {
  const text = typeof value === 'string' ? value : String(value);
  const isNegative = text.trimStart().startsWith('-');
  const unsigned = text.trim().replace(/^[+-]/, '').replace(EXISTING_SEPARATORS, '');

  const [whole, fraction] = unsigned.split('.');
  const grouped = (whole || '0').replace(
    /\B(?=(\d{3})+(?!\d))/g,
    THOUSANDS_SEPARATOR
  );
  const rebuilt = fraction
    ? `${grouped}${DECIMAL_SEPARATOR}${fraction}`
    : grouped;

  return `${isNegative ? MINUS_SIGN : ''}${toPersianDigits(rebuilt)}`;
}

/**
 * Round to a fixed number of decimals, once, as a number.
 *
 * `toFixed` rounds the value it is handed, and that value is usually the result
 * of a division, so it arrives carrying a binary error and two screens computing
 * the same percentage by different routes can print different last digits. Rounding
 * to the target precision as a number first, and building the decimal string from
 * that, removes the second rounding from disagreeing with the first.
 *
 * What it does *not* remove is a value sitting exactly on a rounding tie. A
 * 36.85% change is a half-tenth, and whether the double that represents it lands
 * just above or just below decides whether this prints `36.8` or `36.9` - an
 * error of about 1e-14 in the input, invisible and unavoidable. So this function
 * is not a claim of exact decimal arithmetic, and a test that pins the last digit
 * of a percentage that lands on a tie is pinning a coin flip. `formatChange`'s
 * tests assert one decimal place and the sign, which is what the figure is for.
 */
function round(value: number, digits: number): number {
  const factor = 10 ** digits;
  return Math.round(value * factor) / factor;
}

/**
 * Rial, grouped, with no decimals.
 *
 * Rial amounts are integers in practice and a `.00` on a tender figure invites
 * the reader to think a fractional amount is in play, so the fraction is dropped
 * rather than rendered. The rounding is done on the magnitude, so a price that
 * arrived as a float lands on the rial the operator would quote.
 */
export function formatRial(value: number | null | undefined): string {
  if (value === null || value === undefined || !Number.isFinite(value)) {
    return ABSENT;
  }
  return toPersianNumber(Math.round(value));
}

/**
 * A share of a whole, as a percentage.
 *
 * `digits` is the number of decimal places and defaults to 0, because a weight is
 * a headline figure: "35%" is what goes in the document, and "35.00%" is noise.
 * A caller that needs more precision asks for it, and gets it here rather than
 * by re-implementing the conversion at the call site.
 */
export function formatPercent(
  fraction: number | null | undefined,
  digits = 0
): string {
  if (fraction === null || fraction === undefined || !Number.isFinite(fraction)) {
    return ABSENT;
  }
  return toPersianNumber(round(fraction * 100, digits).toFixed(digits)) + PERCENT_SIGN;
}

/**
 * A signed percentage change, e.g. `+۳۶٫۸٪` or `−۱۰٫۰٪`.
 *
 * The sign is always present, including when it is positive, because the number
 * is read in a column of changes and a missing `+` makes a rise indistinguishable
 * from a smaller rise.
 *
 * One decimal place, and that is not a display preference. A tender's price
 * movement is often a few percent, and rounding those to whole percents turns a
 * 0.4% rise into "0%" - which reads as "the price did not move" and is a claim
 * the reader has no way to disprove from the table.
 *
 * A zero base has no percentage at all, and returns the em dash rather than 0%
 * or Infinity. The base price of a legitimately free-supply item is zero, and
 * "0%" there would say its price did not change, which is a different and wrong
 * statement about a quantity that does not exist.
 */
export function formatChange(
  from: number | null | undefined,
  to: number | null | undefined
): string {
  if (
    from === null ||
    to === null ||
    from === undefined ||
    to === undefined ||
    !Number.isFinite(from) ||
    !Number.isFinite(to) ||
    from === 0
  ) {
    return ABSENT;
  }
  const change = (to - from) / Math.abs(from);
  const sign = change < 0 ? MINUS_SIGN : PLUS_SIGN;
  return `${sign}${toPersianNumber(round(Math.abs(change) * 100, 1).toFixed(1))}${PERCENT_SIGN}`;
}

/** The placeholders used when a value is genuinely absent, not zero. */
export const ABSENT = '—';

// --- Jalali calendar --------------------------------------------------------
//
// Mirrors backend/src/services/_jalali_calendar.py. See the module docstring:
// the algorithm is a direct port so the dashboard and the defence document
// cannot disagree about a tender's date.

/** Jalali years at which the 2820-year cycle's intercalation pattern shifts. */
const CYCLE_BREAKS = [
  -61, 9, 38, 199, 426, 686, 756, 818, 1111, 1181, 1210, 1635, 2060, 2097, 2192,
  2262, 2324, 2394, 2456, 3178,
] as const;

/** Truncated toward zero, as the reference algorithm's integer division is. */
function div(numerator: number, denominator: number): number {
  const quotient = Math.trunc(numerator / denominator);
  return quotient;
}

/** Remainder with the sign of the dividend, matching the reference. */
function mod(numerator: number, denominator: number): number {
  return numerator - div(numerator, denominator) * denominator;
}

function gregorianToJdn(gy: number, gm: number, gd: number): number {
  const monthShift = div(gm - 8, 6);
  const shiftedYear = gy + 100100 + monthShift;

  let dayNumber =
    div(shiftedYear * 1461, 4) + div(153 * mod(gm + 9, 12) + 2, 5) + gd - 34840408;
  dayNumber -= div(div(shiftedYear, 100) * 3, 4) - 752;
  return dayNumber;
}

/** The leap flag and Nowruz Gregorian date for one Jalali year. */
interface JalaliCal {
  /** 0 marks a leap year; 4 the exceptional five-year gap between groups. */
  leap: number;
  gy: number;
  /** The Gregorian day-of-March that is 1 Farvardin. */
  march: number;
}

function jalaliCal(jy: number, withoutLeap = false): JalaliCal {
  const last = CYCLE_BREAKS.length - 1;
  const gy = jy + 621;
  let leapJ = -14;
  // Explicitly `number`, not the literal type: `CYCLE_BREAKS` is `as const`, and
  // inferring `jp` from its first element would give it the type `-61`, which
  // every later assignment then fails against.
  let jp: number = CYCLE_BREAKS[0];
  let jump = 0;

  if (jy < jp || jy >= CYCLE_BREAKS[last]) {
    throw new RangeError(
      `Jalali year ${jy} is outside the range the calendar is defined for ` +
        `(${CYCLE_BREAKS[0]} to ${CYCLE_BREAKS[last] - 1})`
    );
  }

  for (let i = 1; i <= last; i += 1) {
    const jm = CYCLE_BREAKS[i];
    jump = jm - jp;
    if (jy < jm) {
      break;
    }
    leapJ += div(jump, 33) * 8 + div(mod(jump, 33), 4);
    jp = jm;
  }

  let n = jy - jp;
  leapJ += div(n, 33) * 8 + div(mod(n, 33) + 3, 4);
  if (mod(jump, 33) === 4 && jump - n === 4) {
    leapJ += 1;
  }

  const leapG = div(gy, 4) - div((div(gy, 100) + 1) * 3, 4) - 150;
  const march = 20 + leapJ - leapG;

  let leap = 0;
  if (!withoutLeap) {
    if (jump - n < 6) {
      n = n - jump + div(jump + 4, 33) * 33;
    }
    leap = mod(mod(n + 1, 33) - 1, 4);
    if (leap === -1) {
      leap = 4;
    }
  }

  return { leap, gy, march };
}

/** True when Esfand of `jy` has 30 days. */
export function isLeapJalali(jy: number): boolean {
  return jalaliCal(jy).leap === 0;
}

export function daysInJalaliMonth(jy: number, jm: number): number {
  if (jm < 1 || jm > 12) {
    throw new RangeError(`Invalid Jalali month: ${jm}`);
  }
  if (jm <= 6) {
    return 31;
  }
  if (jm <= 11) {
    return 30;
  }
  return isLeapJalali(jy) ? 30 : 29;
}

/**
 * Jalali date -> day number counted from 1 March 622.
 *
 * The inverse of {@link dayNumberToJalali}, and exported so the round trip can
 * be asserted rather than assumed. A conversion whose forward direction is only
 * ever tested against one hand-picked date is a conversion that has never been
 * tested across a year boundary.
 */
function jalaliToJdn(jy: number, jm: number, jd: number): number {
  const cal = jalaliCal(jy, true);
  const base = gregorianToJdn(cal.gy, 3, cal.march);
  return base + (jm - 1) * 31 - div(jm, 7) * (jm - 7) + jd - 1;
}

/**
 * Jalali date -> day number counted from 1 March 622.
 *
 * The inverse of {@link dayNumberToJalali}, and exported so the round trip can
 * be asserted rather than assumed. A conversion whose forward direction is only
 * ever checked against one hand-picked date is a conversion that has never been
 * tested across a year boundary - and a calendar conversion is exactly where a
 * bug hides, because the one date a developer looks at is always right.
 */
export function jalaliToDayNumber(jy: number, jm: number, jd: number): number {
  return jalaliToJdn(jy, jm, jd);
}

/** A Jalali calendar date. */
export interface JalaliDate {
  jy: number;
  jm: number;
  jd: number;
}

/** Day number counted from 1 March 622 -> Jalali `(jy, jm, jd)`. */
export function dayNumberToJalali(dayNumber: number): JalaliDate {
  // The Gregorian year is needed first, because the Jalali year is derived from
  // it and the two disagree around Nowruz. Inlining an approximation of the
  // first step here is exactly the kind of shortcut that puts a day's error in a
  // tender, so the full conversion is used.
  return gregorianFromDayNumber(dayNumber);
}

function gregorianFromDayNumber(dayNumber: number): JalaliDate {
  let j = 4 * dayNumber + 139361631;
  j += div(div(4 * dayNumber + 183187720, 146097) * 3, 4) * 4 - 3908;
  const i = div(mod(j, 1461), 4) * 5 + 308;
  const gd = div(mod(i, 153), 5) + 1;
  const gm = mod(div(i, 153), 12) + 1;
  const gy = div(j, 1461) - 100100 + div(8 - gm, 6);

  const jy = gy - 621;
  const march = jalaliCal(jy).march;
  let dayOfYear = dayNumber - gregorianToJdn(gy, 3, march);

  if (dayOfYear >= 0) {
    if (dayOfYear <= 185) {
      return { jy, jm: 1 + div(dayOfYear, 31), jd: mod(dayOfYear, 31) + 1 };
    }
    dayOfYear -= 186;
  } else {
    // Before Nowruz: the tail of the previous Jalali year.
    const previous = jy - 1;
    dayOfYear += isLeapJalali(previous) ? 180 : 179;
    return {
      jy: previous,
      jm: 7 + div(dayOfYear, 30),
      jd: mod(dayOfYear, 30) + 1,
    };
  }

  return { jy, jm: 7 + div(dayOfYear, 30), jd: mod(dayOfYear, 30) + 1 };
}

/** A Gregorian calendar date. */
export interface GregorianDate {
  year: number;
  month: number;
  day: number;
}

/**
 * Parse an ISO-8601 date, taking the calendar day as written.
 *
 * The reason this is not `new Date(iso)` followed by reading the local fields:
 * `new Date('2026-03-21')` is parsed by the spec as **UTC** midnight, and
 * reading `getDate()` from it in any negative-offset zone returns 20 March. For
 * a tender that crosses a Nowruz boundary that silently shifts the base date of
 * an index by a day, which changes the index ratio and therefore the price. The
 * date is a calendar label here, not an instant, so it is parsed as one.
 */
export function parseIsoDate(iso: string): GregorianDate {
  const match = /^(\d{4})-(\d{2})-(\d{2})/.exec(iso);
  if (!match) {
    throw new TypeError(`Not an ISO-8601 date: ${iso}`);
  }
  return {
    year: Number(match[1]),
    month: Number(match[2]),
    day: Number(match[3]),
  };
}

/** Proleptic Gregorian day number counted from 1 March 622. */
export function gregorianToDayNumber(date: GregorianDate): number {
  return gregorianToJdn(date.year, date.month, date.day);
}

/** A Jalali calendar date, from an ISO-8601 string. */
export function toJalali(iso: string): JalaliDate {
  return dayNumberToJalali(gregorianToDayNumber(parseIsoDate(iso)));
}

/** The Jalali month names, Farvardin first. */
export const JALALI_MONTHS = [
  'فروردین',
  'اردیبهشت',
  'خرداد',
  'تیر',
  'مرداد',
  'شهریور',
  'مهر',
  'آبان',
  'آذر',
  'دی',
  'بهمن',
  'اسفند',
] as const;

export const JALALI_WEEKDAYS = [
  'یکشنبه',
  'دوشنبه',
  'سه‌شنبه',
  'چهارشنبه',
  'پنجشنبه',
  'جمعه',
  'شنبه',
] as const;

/**
 * A Jalali date as Persian text, e.g. `۲۷ شهریور ۱۴۰۵`.
 *
 * The month is named rather than numbered: a reader of an Iranian tender knows
 * the months by name, and "۶" is ambiguous between a Gregorian June and a
 * Jalali Shahrivar on a document that carries both.
 */
export function formatJalali(iso: string, withWeekday = false): string {
  const { jy, jm, jd } = toJalali(iso);
  const date = `${toPersianDigits(String(jd))} ${JALALI_MONTHS[jm - 1]} ${toPersianDigits(String(jy))}`;
  if (!withWeekday) {
    return date;
  }
  // Day 0 of the day-number count is 1 March 622, a Saturday in the proleptic
  // Gregorian calendar, which is why the weekday index is taken modulo the
  // number of days rather than from a separate table.
  const weekday = mod(gregorianToDayNumber(parseIsoDate(iso)) + 1, 7);
  return `${JALALI_WEEKDAYS[weekday]} ${date}`;
}

/**
 * A Jalali date as a number, e.g. `۱۴۰۳/۰۵/۱۲`.
 *
 * The form the defence document uses by default. It exists alongside
 * `formatJalali` rather than replacing it because the backend offers both:
 * `format_jalali(value)` returns this numeric form, and `long_form=True` returns
 * the named one. A column that has to line up under a date in the document gets
 * this; prose gets the named form.
 *
 * The order is year/month/day, not day/month/year. That is the backend's
 * convention (`JalaliDate.to_persian_digits` formats `year/month/day`) and the
 * convention Persian documents use, and it is the reverse of the ISO string this
 * function is given - so the conversion is not a digit swap and cannot be done by
 * substitution.
 *
 * Zero-padded, because an unpadded `۱۴۰۳/۵/۱۲` is ambiguous about whether the
 * month is 5 or 5-something when it sits in a column of dates.
 */
export function formatJalaliNumeric(iso: string): string {
  const { jy, jm, jd } = toJalali(iso);
  return toPersianDigits(
    `${jy}/${String(jm).padStart(2, '0')}/${String(jd).padStart(2, '0')}`
  );
}

/**
 * Both calendars for one ISO date, for a column that has to show both.
 *
 * The Gregorian side is built with `toPersianDigits` and an explicit `/`, and not
 * by passing an ISO string to `toPersianNumber`. The number formatter groups
 * thousands, so handing it `2026-09-28` produces `۲٬۰۲۶-۰۹-۲۸` - a thousands
 * separator inside a year, and ASCII hyphens that the bidi algorithm reorders in
 * an RTL run. The two formatters are for different units; a date is not a number
 * that happens to contain dashes.
 */
export function formatDualDate(iso: string): { jalali: string; gregorian: string } {
  const { year, month, day } = parseIsoDate(iso);
  return {
    jalali: formatJalali(iso),
    gregorian: toPersianDigits(
      `${year}/${String(month).padStart(2, '0')}/${String(day).padStart(2, '0')}`
    ),
  };
}

/**
 * Left-to-right isolate markers, for a number embedded in Persian prose.
 *
 * A rial amount inside a sentence renders its digits in reverse order without
 * them: "قیمت ۱٬۲۵۰٬۰۰۰ ریال" comes out with the digits reversed, because a run
 * of Persian digits is a strong right-to-left sequence and the surrounding
 * punctuation is not. The markers pin the numeric run without changing the visual
 * order of the sentence around it.
 */
export function ltrIsolate(text: string): string {
  return `\u2066${text}\u2069`;
}
